name: Playwright Tests

env:
  PORT: "3003"
  SECRET: ${{ secrets.SECRET }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: true
        default: 'lts/*'
        type: string

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
          ${{ runner.os }}-
    
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci

    - name: Get installed Playwright version
      id: playwright-version
      run: cd ./E2E && echo "PLAYWRIGHT_VERSION=$(npm list @playwright/test | grep '@playwright/test' | awk -F '@' '{print $3}')" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers 
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Build app
      run: npm run build
    
    # - name: Run Playwright tests
    #   run: npm run test:e2e
      
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: ./E2E/playwright-report/
    #     retention-days: 30